[Terrafrom] Add rate limiting
port-labs/ocean pull request #1084
Opened 2024-10-18 17:03 UTC by phalbert

# Description

**What** - This PR implements rate limiting logic in the Terraform Cloud integration to address frequent `429 Too Many Requests` warnings in the logs.

**Why** - We were experiencing excessive `429 Too Many Requests` warnings, indicating that our integration was exceeding Terraform Cloud's API rate limits. This was cluttering the logs and potentially impacting performance.

**How** - Implemented a more robust rate limiting mechanism in the `TerraformClient` class:
1. Added a `wait_for_rate_limit` method to enforce rate limits.
2. Implemented a [token bucket algorithm](https://medium.com/@sumit-s/token-bucket-algorithm-a-laymans-guide-to-rate-limiting-b1ced8d0ee8e#:~:text=The%20Token%20Bucket%20Algorithm%20is,requests%20a%20user%20can%20make.) to manage API request rates.
3. Added asyncio locks to ensure thread-safe rate limiting in asynchronous operations.
4. Updated the `send_api_request` method to use the new rate limiting logic.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

<h4> All tests should be run against the port production environment(using a testing org). </h4>

### Core testing checklist

- [x] Integration able to create all default resources from scratch
- [x] Resync finishes successfully
- [x] Resync able to create entities
- [x] Resync able to update entities
- [x] Resync able to detect and delete entities
- [x] Scheduled resync able to abort existing resync and start a new one
- [x] Tested with at least 2 integrations from scratch
- [x] Tested with Kafka and Polling event listeners
- [x] Tested deletion of entities that don't pass the selector

### Integration testing checklist

- [x] Integration able to create all default resources from scratch
- [x] Resync able to create entities
- [x] Resync able to update entities
- [x] Resync able to detect and delete entities
- [x] Resync finishes successfully
- [ ] If new resource kind is added or updated in the integration, add example raw data, mapping and expected result to the `examples` folder in the integration directory.
- [ ] If resource kind is updated, run the integration with the example data and check if the expected result is achieved
- [ ] If new resource kind is added or updated, validate that live-events for that resource are working as expected
- [ ] Docs PR link [here](#)

### Preflight checklist

- [x] Handled rate limiting
- [x] Handled pagination
- [x] Implemented the code in async
- [x] Support Multi account

## Screenshots

[Include screenshots of logs showing reduced 429 warnings, if available]

## API Documentation

- [Terraform Cloud API Rate Limiting Documentation](https://developer.hashicorp.com/terraform/cloud-docs/api-docs#rate-limiting)

2024-10-22 05:35 UTC, mk-armah requested changes
Great work 👏🏽, left few comments. Also I was wondering if we could use aiolimiter to control requests easily since [terraform rate limit](https://developer.hashicorp.com/terraform/cloud-docs/api-docs#rate-limiting) is time bound

2024-10-22 05:35 UTC, mk-armah commented on integrations/terraform-cloud/main.py
> +            chunk_results = await gather(*[fetch_runs_for_workspace(w) for w in chunk])
Is there a specific reason for replacing as_completed with gather ? waiting for all tasks within a chunk to complete before moving on to the next chunk appears to impede performance in this context. Please correct me.

2024-10-22 05:35 UTC, mk-armah commented on integrations/terraform-cloud/client.py
> +            self.request_times.append(current_time)
[aiolimiter](https://aiolimiter.readthedocs.io/en/latest/) ?

2024-10-30 23:52 UTC, phalbert commented
close for fresh impl in https://github.com/port-labs/ocean/pull/1110 with [aiolimiter](https://pypi.org/project/aiolimiter/)

2024-10-30 23:52 UTC, closed without merging

2024-10-31 00:04 UTC, phalbert commented on integrations/terraform-cloud/client.py
> +MAX_CONCURRENT_REQUESTS = 10
10 is how many workspaces we will process concurrently when fetching runs (or enriching these workspaces).