Port 10905 ocean rate limiting handling from snyk
port-labs/ocean pull request #1092
Opened 2024-10-21 22:02 UTC by oiadebayo

# Description

What -
Implemented rate limiting and concurrency control in the SnykClient to manage API requests effectively. Added a RateLimiter class that controls both the number of requests per minute and the maximum concurrent requests.

Why -
To ensure that our application adheres to the API provider’s rate limit of 1600 requests per minute, while also preventing excessive load by limiting concurrent requests to 1000. This is necessary to avoid getting blocked by the API and to manage resource consumption effectively.

How -

Introduced a RateLimiter class with:

- A BoundedSemaphore to control concurrency (concurrency_limit set to 1000 and api rate to 1320).
- A rate limit mechanism to track requests made within a minute, pausing if the limit is reached.

Used time.monotonic() to reliably track elapsed time and reset the request count every 60 seconds.
Modified the _send_api_request() function to acquire and release the rate limiter, ensuring compliance with both concurrency and rate limits.

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New Integration (non-breaking change which adds a new integration)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Non-breaking change (fix of existing functionality that will not change current behavior)
- [ ] Documentation (added/updated documentation)

<h4> All tests should be run against the port production environment(using a testing org). </h4>

### Core testing checklist

- [ ] Integration able to create all default resources from scratch
- [ ] Resync finishes successfully
- [ ] Resync able to create entities
- [ ] Resync able to update entities
- [ ] Resync able to detect and delete entities
- [ ] Scheduled resync able to abort existing resync and start a new one
- [ ] Tested with at least 2 integrations from scratch
- [ ] Tested with Kafka and Polling event listeners
- [ ] Tested deletion of entities that don't pass the selector

### Integration testing checklist

- [ ] Integration able to create all default resources from scratch
- [ ] Resync able to create entities
- [ ] Resync able to update entities
- [ ] Resync able to detect and delete entities
- [ ] Resync finishes successfully
- [ ] If new resource kind is added or updated in the integration, add example raw data, mapping and expected result to the `examples` folder in the integration directory.
- [ ] If resource kind is updated, run the integration with the example data and check if the expected result is achieved
- [ ] If new resource kind is added or updated, validate that live-events for that resource are working as expected
- [ ] Docs PR link [here](#)

### Preflight checklist

- [ ] Handled rate limiting
- [ ] Handled pagination
- [ ] Implemented the code in async
- [ ] Support Multi account

## Screenshots

Include screenshots from your environment showing how the resources of the integration will look.

## API Documentation

Provide links to the API documentation used for this integration.

2024-10-23 08:08 UTC, mk-armah requested changes

2024-10-23 08:08 UTC, mk-armah commented on integrations/snyk/snyk/rate_limit.py
> +        self.semaphore.release()
Does snyk have concurrency limits ?
Is their rate limit bounded by both time and concurrent requests

2024-10-30 10:11 UTC, PeyGis approved these changes

2024-11-05 12:06 UTC, PeyGis requested changes
one minor change

2024-11-05 12:06 UTC, PeyGis commented on integrations/snyk/main.py
> +SNYK_LIMIT = int(ocean.integration_config.get("snyk_rate_limit", "0"))
since we have provided a default, we can use the square bracket to access the `snyk_rate_limit`

2024-11-05 12:06 UTC, PeyGis commented on integrations/snyk/CHANGELOG.md
> +
remove this

2024-11-05 13:11 UTC, PeyGis approved these changes
lgtm

2024-11-06 21:51 UTC, Tankilevitch commented on integrations/snyk/.port/spec.yaml
> +    description: The API limit enforced by Snyk. The default is 80% of the 1650 requests per minute allowed by Snyk (<a href="https://docs.snyk.io/snyk-api/rest-api/about-the-rest-api#rate-limiting"
I didn't explained it right, my bad, but I meant to have it specified as a const

2024-11-06 21:51 UTC, Tankilevitch commented on integrations/snyk/.port/spec.yaml
> +    description: The API limit enforced by Snyk. The default is 80% of the 1650 requests per minute allowed by Snyk (<a href="https://docs.snyk.io/snyk-api/rest-api/about-the-rest-api#rate-limiting"
Lets not expose it for now to the customer

2024-11-19 09:29 UTC, merged