[Core] Support the reduction of Port rate limit in the integrations
port-labs/ocean pull request #1155
Opened 2024-11-20 09:34 UTC by shalev007

# Description

What - I updated the retry mechanism to ensure the total retry time is capped at 5 minutes, with a maximum backoff time of 5 minutes between retries.

Why - This change is needed to handle the reduced port rate limit in integrations more effectively, minimizing the risk of overwhelming the system while still ensuring retries are reasonable.

How - I adjusted the retry logic to distribute retries over the 5-minute window, scaling backoff times to align with the reduced rate limit without exceeding the time limit.

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New Integration (non-breaking change which adds a new integration)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Non-breaking change (fix of existing functionality that will not change current behavior)
- [ ] Documentation (added/updated documentation)

<h4> All tests should be run against the port production environment(using a testing org). </h4>

### Core testing checklist

- [ ] Integration able to create all default resources from scratch
- [ ] Resync finishes successfully
- [ ] Resync able to create entities
- [ ] Resync able to update entities
- [ ] Resync able to detect and delete entities
- [ ] Scheduled resync able to abort existing resync and start a new one
- [ ] Tested with at least 2 integrations from scratch
- [ ] Tested with Kafka and Polling event listeners
- [ ] Tested deletion of entities that don't pass the selector

### Integration testing checklist

- [ ] Integration able to create all default resources from scratch
- [ ] Resync able to create entities
- [ ] Resync able to update entities
- [ ] Resync able to detect and delete entities
- [ ] Resync finishes successfully
- [ ] If new resource kind is added or updated in the integration, add example raw data, mapping and expected result to the `examples` folder in the integration directory.
- [ ] If resource kind is updated, run the integration with the example data and check if the expected result is achieved
- [ ] If new resource kind is added or updated, validate that live-events for that resource are working as expected
- [ ] Docs PR link [here](#)

### Preflight checklist

- [ ] Handled rate limiting
- [ ] Handled pagination
- [ ] Implemented the code in async
- [ ] Support Multi account

## Screenshots

Include screenshots from your environment showing how the resources of the integration will look.

## API Documentation

Provide links to the API documentation used for this integration.

2024-11-20 15:42 UTC, Tankilevitch requested changes
missing changelog and version bump

2024-11-20 15:42 UTC, Tankilevitch commented on port_ocean/helpers/retry.py
> +    MAX_BACKOFF_WAIT = 60 * 5  # 5 minutes
```suggestion
    MAX_BACKOFF_WAIT_IN_SECONDS = 60 * 5
```

2024-11-20 15:42 UTC, Tankilevitch commented on port_ocean/helpers/retry.py
> +    MAX_BACKOFF_WAIT = 60 * 5  # 5 minutes
changing this here will effect both port client and all integrations clients, is it intended?

2024-11-20 16:42 UTC, Tankilevitch approved these changes

2024-11-21 10:55 UTC, erikzaadi approved these changes
1 NITs
<img src="https://media1.giphy.com/media/vgUFOWBwBkziE/giphy.gif"/>

2024-11-21 10:55 UTC, erikzaadi commented on port_ocean/clients/port/utils.py
> +                "max_backoff_wait": 60 * 5,
Extract the `5` to a named const

2024-11-21 10:55 UTC, erikzaadi commented on port_ocean/clients/port/utils.py
> +PORT_HTTP_MAX_CONNECTIONS_LIMIT = 100
Wonder if it's worth having this configurable by env var for quick patches/tests later on

2024-11-25 10:05 UTC, merged