[Integration][GCP] Fixed issues preventing the proper processing of real-time events
port-labs/ocean pull request #1247
Opened 2024-12-17 12:57 UTC by oiadebayo

# Description

What - Updated the `should_use_snake_case` function to support real time event processing by allowing it to use matching_resource_configs when processing real-time events. Resync processes continue using the existing implementation with get_current_resource_config()

Why - The previous implementation relied solely on get_current_resource_config(), which is unsuitable for webhook event processing because the `event.resource_config` used for resync events returns `None` during realtime events

How - Modified the `should_use_snake_case` function to accept an optional `matching_resource_configs` parameter and also updated the `feed_events_callback` function to `pass matching_resource_configs` to `should_use_snake_case` during webhook processing

## Type of change

Please leave one option from the following and delete the rest:

- [x] Bug fix (non-breaking change which fixes an issue)

<h4> All tests should be run against the port production environment(using a testing org). </h4>

### Core testing checklist

- [ ] Integration able to create all default resources from scratch
- [ ] Resync finishes successfully
- [ ] Resync able to create entities
- [ ] Resync able to update entities
- [ ] Resync able to detect and delete entities
- [ ] Scheduled resync able to abort existing resync and start a new one
- [ ] Tested with at least 2 integrations from scratch
- [ ] Tested with Kafka and Polling event listeners
- [ ] Tested deletion of entities that don't pass the selector

### Integration testing checklist

- [ ] Integration able to create all default resources from scratch
- [ ] Resync able to create entities
- [ ] Resync able to update entities
- [ ] Resync able to detect and delete entities
- [ ] Resync finishes successfully
- [ ] If new resource kind is added or updated in the integration, add example raw data, mapping and expected result to the `examples` folder in the integration directory.
- [ ] If resource kind is updated, run the integration with the example data and check if the expected result is achieved
- [ ] If new resource kind is added or updated, validate that live-events for that resource are working as expected
- [ ] Docs PR link [here](#)

### Preflight checklist

- [ ] Handled rate limiting
- [ ] Handled pagination
- [ ] Implemented the code in async
- [ ] Support Multi account

## Screenshots

Include screenshots from your environment showing how the resources of the integration will look.

## API Documentation

Provide links to the API documentation used for this integration.

2024-12-18 11:22 UTC, mk-armah requested changes
Changes required

2024-12-18 11:22 UTC, mk-armah commented on integrations/gcp/main.py
> +            asset_type, asset_name, asset_project, asset_data, matching_resource_configs
if there are no matching configs, I'm not sure why we should consider continuing processing, perhaps we can log that the kind does not exist, feel free to let me what you think. This goes on to affect downstream types and precessing too

2024-12-18 11:22 UTC, mk-armah commented on integrations/gcp/gcp_core/search/resource_searches.py
> +    matching_resource_configs: list[Any] = [],
please add the appropriate type hint here instead of Any

2024-12-18 11:22 UTC, mk-armah commented on integrations/gcp/gcp_core/utils.py
> +            return True
returning True will convert to camelCase, that's not the difficult behavior, correct me if I'm wrong here.

2024-12-18 11:22 UTC, mk-armah commented on integrations/gcp/gcp_core/utils.py
> +        resource = next(iter(matching_resource_configs), None)
What happens when there are more than one config in the array ? See comment in main.py on how to resolve this

2024-12-18 11:22 UTC, mk-armah commented on integrations/gcp/main.py
> +            asset_type, asset_name, asset_project, asset_data, matching_resource_configs
Iterate over matching_resource_config to register `asset_resource_data` for each kind that is a match

2024-12-23 11:53 UTC, phalbert approved these changes
LGTM

2024-12-23 14:34 UTC, matan84 requested changes
requested changes

2024-12-23 14:34 UTC, matan84 commented on integrations/gcp/gcp_core/utils.py
> +    )
```suggestion
    preserve_api_case =  getattr(selector, "preserve_api_response_case_style", False)
```

2024-12-23 14:34 UTC, matan84 commented on integrations/gcp/gcp_core/utils.py
> +    matching_resource_configs: Optional[GCPResourceConfig] = None,
```suggestion
    preserving_proto_field_name: bool = False,
```

2024-12-23 14:34 UTC, matan84 commented on integrations/gcp/gcp_core/search/resource_searches.py
> +    matching_resource_config: Optional[GCPResourceConfig] = None,
```suggestion
    preserving_proto_field_name: bool = False,
```

2024-12-28 15:25 UTC, matan84 approved these changes
LGTM

2024-12-28 15:29 UTC, merged