[Core] Add metrics for ocean core
port-labs/ocean pull request #1260
Opened 2024-12-23 13:23 UTC by ivankalinovski

1. Decorator that can be used to "metricify" a function - accepts phase as input.
2. Auto record duration.
3. `increment_field` method for handling counters.
4. `increment_status` method for handling requests.
5. populate event with `MetricAggregator` to track metrics.

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New Integration (non-breaking change which adds a new integration)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Non-breaking change (fix of existing functionality that will not change current behavior)
- [ ] Documentation (added/updated documentation)

<h4> All tests should be run against the port production environment(using a testing org). </h4>

### Core testing checklist

- [ ] Integration able to create all default resources from scratch
- [ ] Resync finishes successfully
- [ ] Resync able to create entities
- [ ] Resync able to update entities
- [ ] Resync able to detect and delete entities
- [ ] Scheduled resync able to abort existing resync and start a new one
- [ ] Tested with at least 2 integrations from scratch
- [ ] Tested with Kafka and Polling event listeners
- [ ] Tested deletion of entities that don't pass the selector

### Integration testing checklist

- [ ] Integration able to create all default resources from scratch
- [ ] Resync able to create entities
- [ ] Resync able to update entities
- [ ] Resync able to detect and delete entities
- [ ] Resync finishes successfully
- [ ] If new resource kind is added or updated in the integration, add example raw data, mapping and expected result to the `examples` folder in the integration directory.
- [ ] If resource kind is updated, run the integration with the example data and check if the expected result is achieved
- [ ] If new resource kind is added or updated, validate that live-events for that resource are working as expected
- [ ] Docs PR link [here](#)

### Preflight checklist

- [ ] Handled rate limiting
- [ ] Handled pagination
- [ ] Implemented the code in async
- [ ] Support Multi account

## Screenshots

Include screenshots from your environment showing how the resources of the integration will look.

## API Documentation

Provide links to the API documentation used for this integration.

2025-01-04 19:54 UTC, Tankilevitch requested changes

2025-01-04 19:54 UTC, Tankilevitch commented on port_ocean/helpers/metric.py
> +def metric(phase: str | None = None, should_capture_time: bool = True) -> Any:
add docs

2025-01-04 19:54 UTC, Tankilevitch commented on port_ocean/helpers/metric.py
> +async def timed_generator(
add docs

2025-01-04 19:54 UTC, Tankilevitch commented on scripts/run-compare-diff-pef.sh
this file is very hard to understand and missing docs, is this really needed?

2025-01-04 19:54 UTC, Tankilevitch commented on port_ocean/tests/test_metric.py
can we also have unit tests? for the whole metric capability?

2025-01-04 19:54 UTC, Tankilevitch commented on port_ocean/tests/test_metric.py
> +    fake_person = metrics["fake-person"]
what `fake-person` mean in a metric? I understand that its contains the `extract`, `load` `transform` but I wonder how we can monitor that?

2025-01-04 19:54 UTC, Tankilevitch commented on port_ocean/context/event.py
> +    is_silent = EventType.METRIC == event_type
why this is needed for?

2025-01-04 19:54 UTC, Tankilevitch commented on port_ocean/helpers/metric.py
> +                break
why `break`? how the `exception` is being propogated? its not equivalent to the way you are iterating over  when `if not port_ocean.context.event.event.should_record_metrics`

2025-01-04 19:54 UTC, Tankilevitch commented on port_ocean/helpers/metric.py
> +            metric.requests[status_code] = metric.requests.get(status_code, 0) + 1
I wonder if this is actually needed 🤔  its sounds too specific, you already implemented `increment_field`

2025-01-04 19:54 UTC, Tankilevitch commented on port_ocean/helpers/metric.py
> +            logger.info(f"integration metrics {json.dumps(metric_dict)}")
please share in the pr description the `flush` output

2025-02-09 14:13 UTC, Tankilevitch commented
/review

2025-02-09 14:14 UTC, Tankilevitch commented
/improve

2025-03-19 20:01 UTC, matan84 approved these changes
Left comments

2025-03-19 20:01 UTC, matan84 commented on scripts/run-local-perf-test.sh
> +    sleep 1
A non-blocker comment, feel free to resolve this
Why?

2025-03-24 11:11 UTC, matan84 approved these changes
<img src="https://media4.giphy.com/media/f2HiQKaEkaKwo/giphy.gif?cid=bd3ea57e6ykflxc2xt28888ebarp10eri2p5jc10knartc0o&ep=v1_gifs_trending&rid=giphy.gif&ct=g"/>

2025-03-24 13:41 UTC, Tankilevitch approved these changes

2025-03-24 14:34 UTC, merged