Added a type to items in arrays for default blueprints
port-labs/ocean pull request #1270
Opened 2024-12-26 09:58 UTC by amitb777

# Description

What -
Added a type to items in arrays for default blueprints. In some cases I guessed the type based on the mapping, so you should validate me before approving.

Why -
The Port's API will soon block the option to have an array prop without items type

How -
Checked the missing props and added types to them.

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New Integration (non-breaking change which adds a new integration)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Non-breaking change (fix of existing functionality that will not change current behavior)
- [ ] Documentation (added/updated documentation)

<h4> All tests should be run against the port production environment(using a testing org). </h4>

### Core testing checklist

- [ ] Integration able to create all default resources from scratch
- [ ] Resync finishes successfully
- [ ] Resync able to create entities
- [ ] Resync able to update entities
- [ ] Resync able to detect and delete entities
- [ ] Scheduled resync able to abort existing resync and start a new one
- [ ] Tested with at least 2 integrations from scratch
- [ ] Tested with Kafka and Polling event listeners
- [ ] Tested deletion of entities that don't pass the selector

### Integration testing checklist

- [ ] Integration able to create all default resources from scratch
- [ ] Resync able to create entities
- [ ] Resync able to update entities
- [ ] Resync able to detect and delete entities
- [ ] Resync finishes successfully
- [ ] If new resource kind is added or updated in the integration, add example raw data, mapping and expected result to the `examples` folder in the integration directory.
- [ ] If resource kind is updated, run the integration with the example data and check if the expected result is achieved
- [ ] If new resource kind is added or updated, validate that live-events for that resource are working as expected
- [ ] Docs PR link [here](#)

### Preflight checklist

- [ ] Handled rate limiting
- [ ] Handled pagination
- [ ] Implemented the code in async
- [ ] Support Multi account

## Screenshots

Include screenshots from your environment showing how the resources of the integration will look.

## API Documentation

Provide links to the API documentation used for this integration.

2024-12-26 11:51 UTC, Tankilevitch requested changes
make sure you bump the integration version in pyproject.toml and add a changelog

2024-12-26 11:51 UTC, Tankilevitch commented on integrations/firehydrant/.port/resources/blueprints.json
> +          },
I don't think its a valid schema

2024-12-26 12:07 UTC, amitb777 commented on integrations/firehydrant/.port/resources/blueprints.json
> +          },
Fixed the typo

2025-01-22 10:09 UTC, Tankilevitch approved these changes
LGTM

2025-01-22 10:56 UTC, merged