terraform project support
port-labs/ocean pull request #305
Opened 2023-12-29 10:48 UTC by mk-armah

# Description

What - Adding support for Terraform Projects

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

2023-12-31 14:40 UTC, Tankilevitch requested changes
minor

2023-12-31 14:40 UTC, Tankilevitch commented on integrations/terraform-cloud/.port/resources/blueprints.json
> +          "organizationId": {
change the order to be in the order of relations for cleaner reading of the blueprints json.

project > workspace > cloudStateversion > cloudRun

2023-12-31 14:40 UTC, Tankilevitch commented on integrations/terraform-cloud/.port/resources/blueprints.json
> +      "mirrorProperties":{},
Relation between project and cluster?

2023-12-31 14:40 UTC, Tankilevitch commented on integrations/terraform-cloud/.port/resources/blueprints.json
> +      "relations":{},
keep the convention of relations being last property

2023-12-31 19:52 UTC, yairsimantov20 requested changes
Comments

2023-12-31 19:52 UTC, yairsimantov20 commented on integrations/terraform-cloud/.port/resources/blueprints.json
> +         "project":{"title":"Terraform Cloud Project",
Format your json please

2023-12-31 19:52 UTC, yairsimantov20 commented on integrations/terraform-cloud/CHANGELOG.md
> +
Be more verbose please

2023-12-31 19:52 UTC, yairsimantov20 commented on integrations/terraform-cloud/main.py
> +        yield project
Better naming please
This is not a single project

2023-12-31 19:52 UTC, yairsimantov20 commented on integrations/terraform-cloud/pyproject.toml
> -version = "0.1.1"
?
Why 2 versions?

2024-01-02 08:59 UTC, mk-armah commented on integrations/terraform-cloud/pyproject.toml
> -version = "0.1.1"
@yairsimantov20 , sorry i don't understand, i'm seeing only one version. 0.1.3

2024-01-02 11:35 UTC, closed without merging