[Integration][Gitlab] Add onboarding default resources
port-labs/ocean pull request #309
Opened 2023-12-31 14:54 UTC by Tankilevitch

# Description

What -
Why -
How -

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Non-breaking change (fix of existing functionality that will not change current behavior)
- [ ] Documentation (added/updated documentation)

2023-12-31 14:56 UTC, Tankilevitch commented
Relies on #308

2023-12-31 19:47 UTC, yairsimantov20 requested changes
I have a feeling questions lets talk about it

2024-01-01 09:16 UTC, yairsimantov20 approved these changes
🌊 verbose changelog

2024-01-02 13:21 UTC, yairsimantov20 approved these changes
🌊

2024-01-02 13:21 UTC, yairsimantov20 commented on integrations/gitlab/gitlab_integration/ocean.py
> +                projects_processed_in_full_batch += len(projects_batch)
```
for index in range(0, len(projects), PROJECT_RESYNC_BATCH_SIZE):
 #  projects_processed_in_full_batch = i  + PROJECT_RESYNC_BATCH_SIZE + 1
  projects_batch = projects[i : i + PROJECT_RESYNC_BATCH_SIZE]

2024-01-02 17:21 UTC, merged