Autodiscover snyk organizations and groups
port-labs/ocean pull request #313
Opened 2024-01-03 16:48 UTC by PeyGis

# Description
We got a feedback from a customer that it’s hard to create an exporter for each organization they have in snyk. And they would prefer to bring all the orgaanizations  on a specific group.

What -
Why -
How - Using config mapping and the token provided in the ocean integration, we fetch all the organizations that are associated with the given token. We then fetch all snyk data (projects, targets, issues) for all organizations. We also make it possible for the user to filter out any specific group, instead of all organizations.

## Type of change

Please leave one option from the following and delete the rest:

- [ ] New feature (non-breaking change which adds functionality)

2024-01-10 07:28 UTC, Tankilevitch requested changes
Some changes are still required, overall nice job 🌊

2024-01-10 07:28 UTC, Tankilevitch commented on integrations/snyk/snyk/client.py
> +            )
this can be done in parallel, instead of one by one

2024-01-10 07:28 UTC, Tankilevitch commented on integrations/snyk/snyk/client.py
> +        # Check if the result is already cached
this function supports bringing orgs from multiple groups, while the method name relates to one group, lets adjust the naming

2024-01-15 16:53 UTC, PeyGis commented on integrations/snyk/main.py
> +        tasks = [process_project_issues(project) for project in projects]
I can bump it to 20 then

2024-01-15 17:09 UTC, PeyGis commented on integrations/snyk/.port/spec.yaml
> +    type: string
The integration docs shows only these types that's why I went for the string

Available values: string, number, boolean, object, url

2024-01-16 07:48 UTC, Tankilevitch commented on integrations/snyk/.port/spec.yaml
> +    type: string
I think we missed it in the docs, but I know that the azure integration uses the list type, can you check it please? if that works I prefer us using list which is more straight forward to the user.

2024-01-16 07:49 UTC, Tankilevitch commented on integrations/snyk/main.py
> +        tasks = [process_project_issues(project) for project in projects]
I found this - https://snyk.docs.apiary.io/#introduction/errors 
so 20 I guess is alright :)

2024-01-16 07:52 UTC, PeyGis commented on integrations/snyk/.port/spec.yaml
> +    type: string
Sure

2024-01-16 08:03 UTC, Tankilevitch requested changes
Looks good

I still think we need to handle the organizations response in a different way, instead of one time bringing the organizations from the rest api and sometimes from the groups api and those be strict with the data that is returned.
Let's pull all the organizations from the API, and filter the unrelated ones from the organizations list that is being returned from the group API.

2024-01-16 11:47 UTC, Tankilevitch approved these changes
LGTM

2024-01-16 13:01 UTC, merged