Port 5981 ocean send logs to an endpoint
port-labs/ocean pull request #371
Opened 2024-01-28 14:05 UTC by yairsimantov20

# Description

What -
Why -
How -

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Non-breaking change (fix of existing functionality that will not change current behavior)
- [ ] Documentation (added/updated documentation)

2024-01-28 14:07 UTC, yairsimantov20 commented on integrations/jira/jira/client.py
> +
revert me

2024-01-28 14:07 UTC, yairsimantov20 commented on port_ocean/consumers/kafka_consumer.py
take care of this

2024-01-28 14:07 UTC, yairsimantov20 commented on port_ocean/ocean.py
> +            sensitive_log_filter.hide_sensitive_tokens(*sensitive)
hide ocean config sensitive configuration. CLIENT_ID SECRET etc...

2024-01-28 14:07 UTC, yairsimantov20 commented on port_ocean/ocean.py
> +            set_signal_handler()
handle for kafka and webhook handlers

2024-01-29 13:02 UTC, Tankilevitch requested changes
Very nice job @yairsimantov20 🚀 🌊 
Left some comments

2024-01-29 13:02 UTC, Tankilevitch commented on port_ocean/utils/signal.py
> +        self._handlers: dict[str, Callable] = {}
Not especially related to the signal class, but I don't see that there is signal handling for all the event listeners ( kafka, once )

2024-01-29 13:58 UTC, yairsimantov20 commented on port_ocean/log/handlers.py
> +EMPTY_LOG_RECORD = LogRecord("", 0, "", 0, "", (), None)
not used anymore

2024-01-29 14:00 UTC, yairsimantov20 commented on port_ocean/log/handlers.py
> +    ):
move the values to the init

2024-01-30 00:33 UTC, yairsimantov20 commented on port_ocean/utils/signal.py
> +        raise RuntimeError("Signal handler is already initialized")
change runtime error with custom ones

2024-01-30 20:27 UTC, Tankilevitch requested changes
minor

2024-01-30 20:27 UTC, Tankilevitch commented on port_ocean/log/sensetive.py
> +    "Cloudinary": r"cloudinary:\/\/.*",
super cool, I am thinking maybe we would like to reduce the amount of patterns to those logically related to what ocean will support exporting. 

e.g. square, twitter sounds too far from integration that will be supported

2024-01-30 20:27 UTC, Tankilevitch commented on port_ocean/config/base.py
> +def _handle_get_sensitive_information(
```suggestion
def _handle_sensitive_information(
```

2024-01-30 20:27 UTC, Tankilevitch commented on port_ocean/ocean.py
> +                logger.exception(f"Failed to start integration with error: {e}")
no need for e when using exception if IIRC

2024-01-30 20:27 UTC, Tankilevitch commented on port_ocean/consumers/kafka_consumer.py
> -from port_ocean.consumers.base_consumer import BaseConsumer
so `baseConsumer` can be deleted?

2024-01-30 20:27 UTC, Tankilevitch commented on port_ocean/consumers/kafka_consumer.py
> +            while self.running and not event.is_set():
very cool

2024-01-30 20:27 UTC, Tankilevitch commented on port_ocean/core/event_listener/base.py
> +        _id = signal_handler.register(self._stop)
redundant `_id`?

2024-01-30 20:27 UTC, Tankilevitch commented on port_ocean/core/event_listener/polling.py
> +from asyncio import Task
choose one

2024-01-31 11:28 UTC, yairsimantov20 commented on port_ocean/consumers/kafka_consumer.py
> -from port_ocean.consumers.base_consumer import BaseConsumer
seed
thought i already did

2024-02-05 12:29 UTC, Tankilevitch approved these changes
LGTM 🌊

2024-02-05 12:29 UTC, Tankilevitch commented on port_ocean/ocean.py
> +        )
```suggestion
        # add the integration sensitive configuration to the sensitive patterns to mask out 
        sensitive_log_filter.hide_sensitive_tokens(
            *self.config.get_sensitive_fields_data()
        )
```

2024-02-18 11:06 UTC, MatanHeledPort approved these changes
lgtm

2024-02-18 11:07 UTC, merged