Updated documentation in spec.yaml
port-labs/ocean pull request #488
Opened 2024-04-05 09:10 UTC by mk-armah

# Description

What - Updated Launchdarkly Documentation Path in spec.yaml
Why - Old path changed

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Documentation (added/updated documentation)

2024-04-05 09:41 UTC, PeyGis requested changes
Yesterday I submitted a [PR](https://github.com/port-labs/port-docs/pull/1075) on the main docs to fix the link so it doesn't show the %20 formatting

2024-04-05 09:41 UTC, PeyGis commented on integrations/launchdarkly/.port/spec.yaml
> +docs: https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/feature%20management/launchdarkly
```suggestion
docs: https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly
```

2024-04-05 12:08 UTC, mk-armah commented
> Yesterday I submitted a [PR](https://github.com/port-labs/port-docs/pull/1075) on the main docs to fix the link so it doesn't show the %20 formatting

cool

2024-04-09 10:01 UTC, PeyGis approved these changes
Looks good to me

2024-04-11 11:17 UTC, closed without merging