[Integration][SonarQube] - Apply Api Filters to Only SonarQube
port-labs/ocean pull request #636
Opened 2024-05-17 13:32 UTC by PeyGis

# Description

What - The integration was throwing HTTP 400 Bad request Error when a user filters the projects on a SonarCloud instance. The filters is only available on SonarQube (on-premise)
Why -
How -

## Type of change

Please leave one option from the following and delete the rest:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New Integration (non-breaking change which adds a new integration)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Non-breaking change (fix of existing functionality that will not change current behavior)
- [ ] Documentation (added/updated documentation)

## Screenshots

<img width="1509" alt="Screenshot 2024-05-17 at 11 23 54 AM" src="https://github.com/port-labs/ocean/assets/15999660/4937d467-8958-4bba-9e89-125b2f0c0c36">

## API Documentation

[SonarCloud get components](https://sonarcloud.io/web_api/api/components?deprecated=false) does not have any filters but [SonarQube get components](https://next.sonarqube.com/sonarqube/web_api/api/components/search_projects?internal=true) does have

2024-06-28 10:07 UTC, Tankilevitch approved these changes

2024-06-28 10:08 UTC, Tankilevitch requested changes

2024-06-28 10:08 UTC, Tankilevitch commented on integrations/sonarqube/client.py
> +                query_params.update(selector.generate_request_params())
lets detect if its not on premise and with api_query_params and raise a warning log

2024-07-22 14:44 UTC, erikzaadi approved these changes
![image](https://cloud.githubusercontent.com/assets/77775/22860323/c73421ac-f102-11e6-93cb-1c71da32e0f0.png)

2024-07-23 12:55 UTC, Tankilevitch approved these changes

2024-07-23 12:58 UTC, merged