Changed fetching to be of latest resource version
port-labs/ocean pull request #648
Opened 2024-05-23 13:38 UTC by matan84

# Description

What - Changed resource fetching to be only on last resource version of the asset
Why - Parsing the asset for each property is redundant
How - Getting the response of the asset, from it return the latest resource

## Type of change

Please leave one option from the following and delete the rest:

- [ ] New feature (non-breaking change which adds functionality)

## API Documentation

https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/

2024-05-23 13:46 UTC, yairsimantov20 requested changes
🌊

2024-05-26 09:57 UTC, Tankilevitch requested changes

2024-05-26 09:57 UTC, Tankilevitch commented on integrations/gcp/gcp_core/search/resource_searches.py
> +                        resources.append(resource)
```suggestion
                        latest_resource = parse_latest_resource_from_asset(asset)
                        latest_resource[EXTRA_PROJECT_FIELD] = project_name
                        latest_resources.append(resource)
```

2024-05-26 09:57 UTC, Tankilevitch commented on integrations/gcp/gcp_core/search/resource_searches.py
> +                        topic[EXTRA_PROJECT_FIELD] = project_name
can we provide it with all the project information? and not only the name?

2024-05-26 09:57 UTC, Tankilevitch commented on integrations/gcp/main.py
> +        )
I think you don't need to do this with @omby8888 feature of delete on event, please verify

2024-05-26 11:44 UTC, Tankilevitch requested changes

2024-05-26 11:44 UTC, Tankilevitch commented on integrations/gcp/.port/resources/blueprints.json
> +    "identifier": "gcpCloudFunctions",
remove

2024-05-26 11:44 UTC, Tankilevitch commented on integrations/gcp/.port/resources/blueprints.json
> +    "identifier": "gcpContainerCluster",
remove

2024-05-26 12:11 UTC, Tankilevitch approved these changes

2024-05-26 12:12 UTC, merged