Improvements to Jenkins integration blueprint
port-labs/ocean pull request #774
Opened 2024-07-04 06:46 UTC by jortegac

# Description

What 
- Add ABORTED to jenkins build status enum. 
- Give url format to jenkins job and build url properties
Why 
- The ABORTED build status allow for visibility on builds that are being aborted
- The URL as base string format look terrible on the UI. With the url format it looks like a nice button
How 
- Changed the blueprint json for Jenkins

## Type of change

Please leave one option from the following and delete the rest:

- [X] Non-breaking change (fix of existing functionality that will not change current behavior)

2024-07-04 12:00 UTC, PeyGis commented
Thanks for the updates @jortegac please add the CHANGELOG.md so we track this improvements. Also bump the integration version in the pyproject.toml

2024-07-04 15:59 UTC, jortegac commented
> Thanks for the updates @jortegac please add the CHANGELOG.md so we track this improvements. Also bump the integration version in the pyproject.toml

Done, @PeyGis . Lemme know if any other changes are needed

2024-11-10 12:54 UTC, shalev007 submitted a review, later dismissed

2024-11-10 13:13 UTC, shalev007 commented
Hey @jortegac Thank you so much for the contribution 🥇,
We'll go over it ASAP, can you pease in the meantime update your branch?
I tried to update it for you but I cannot update your branch directly since it is a fork

2024-11-11 15:11 UTC, phalbert requested changes

2024-11-11 15:11 UTC, phalbert commented on integrations/jenkins/.port/resources/blueprints.json
> +                        "aborted": "gray"
@jortegac, thank you for these changes. Just one comment: gray is not a valid colour option; use `lightGray` instead

2024-11-11 15:11 UTC, phalbert commented on integrations/jenkins/.port/resources/blueprints.json
> +                        "aborted": "gray"
@jortegac once fixed, please merge the main branch into your fork to resolve all the conflicts and then we can merge.

2025-06-08 07:53 UTC, closed without merging