feat:clickup integration
port-labs/ocean pull request #779
Opened 2024-07-04 15:27 UTC by olabanjy

# Description

What - Click Up Integration

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] New Integration (non-breaking change which adds a new integration)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Non-breaking change (fix of existing functionality that will not change current behavior)
- [ ] Documentation (added/updated documentation)

## Screenshots

Include screenshots from your environment showing how the resources of the integration will look.

## API Documentation

Provide links to the API documentation used for this integration.

2024-07-05 03:05 UTC, lordsarcastic requested changes
Good job, fix comments

2024-07-05 03:05 UTC, lordsarcastic commented on integrations/clickup/client.py
> +        while page * self.page_size < len(all_projects):
Is the folders endpoint response paginated? The docs say otherwise

2024-07-05 03:05 UTC, lordsarcastic commented on integrations/clickup/client.py
> +        async for teams in self.get_teams():
Can you refactor this to look cleaner?

2024-07-05 03:05 UTC, lordsarcastic commented on integrations/clickup/client.py
> +        issue_response.raise_for_status()
Catch error, log, rethrow

2024-07-05 03:05 UTC, lordsarcastic commented on integrations/clickup/client.py
> +    async def create_events_webhook(self, app_host: str) -> None:
Not needed

2024-07-05 03:05 UTC, lordsarcastic commented on integrations/clickup/client.py
> +        if not all_issues:
Same comment above regarding incorrect credentials

2024-07-05 03:05 UTC, lordsarcastic commented on integrations/clickup/client.py
> +        while page * self.page_size < len(all_issues):
Is this response really paginated?

2024-07-05 03:05 UTC, lordsarcastic commented on integrations/clickup/client.py
> +        async for teams in self.get_teams():
This could be written in a neater way without 7 nested loops

2024-07-05 03:05 UTC, lordsarcastic commented on integrations/clickup/main.py
> +# Listen to the resync event of all the kinds specified in the mapping inside port.
Take out comment

2024-07-05 03:05 UTC, lordsarcastic commented on integrations/clickup/main.py
> +async def on_start() -> None:
You don't need this since you aren't performing any behaviour on start. You can use this function to do a healthcheck.

2024-07-08 10:28 UTC, PeyGis requested changes
Please go over my comments and apply the fixes. There are several functions that you've created in the client.py but I don't see it used anywhere

2024-07-08 10:28 UTC, PeyGis commented on integrations/clickup/.port/resources/port-app-config.yaml
> +            members: ".members[].user.email"
This will not yield an array [] but a list of emails delimeted by comma. Use '[.members[].user.email]' instead

2024-07-08 10:28 UTC, PeyGis commented on integrations/clickup/.port/spec.yaml
> +    sensitive: true
Is there any reason why you did not add the clickupApiUrl variable?

2024-07-08 10:28 UTC, PeyGis commented on integrations/clickup/CHANGELOG.md
> +# Port_Ocean 1 (2024-07-05)
This should be Port_Ocean 0.1.0

2024-07-08 10:28 UTC, PeyGis commented on integrations/clickup/changelog/1.feature.md
> +clickup integration
Delete this file

2024-07-08 10:28 UTC, PeyGis commented on integrations/clickup/client.py
> +        self.clickup_url = "https://api.clickup.com"
Why are you storing this as a class variable? You can use it directly. Also, I prefer you load it from the integration config, just like you are doing for the clickup_token

2024-07-08 10:28 UTC, PeyGis commented on integrations/clickup/client.py
> +        self.clickup_token = clickup_token
Why do you have to add the token as a class variable? Why can't you use it directly in the auth headers?

2024-07-08 10:28 UTC, PeyGis commented on integrations/clickup/client.py
> +        self.headers = {"Authorization": self.clickup_token}
You can use the Auth header directly in the self.client.headers.update. You don't need to have it as a class variable

2024-07-08 10:28 UTC, PeyGis commented on integrations/clickup/client.py
> +    def _generate_base_req_params(page: int = 0) -> Dict[str, Any]:
let's use `dict` instead of `Dict` and `list` instead of `List`

2024-07-08 10:28 UTC, PeyGis commented on integrations/clickup/client.py
> +        yield team_list
What's the purpose of this function?

2024-07-08 10:28 UTC, PeyGis commented on integrations/clickup/client.py
> +        yield all_spaces
What's the purpose of this

2024-07-08 10:28 UTC, PeyGis commented on integrations/clickup/client.py
> +        all_folders_resp = (await self._get_folders(space_id, params))["folders"]
The folder's endpoint does not support pagination so this `params` will not do anything

2024-07-08 10:28 UTC, PeyGis commented on integrations/clickup/client.py
> +        yield all_projects
What's the purpose of yielding two items here?

2024-07-08 10:28 UTC, PeyGis commented on integrations/clickup/client.py
> +        yield all_issues
The issues endpoint supports pagination but I don't see it used here

2024-07-17 13:35 UTC, closed without merging