[Integration][Dynatrace] Dynatrace bug causing SLO entities to be stale
port-labs/ocean pull request #848
Opened 2024-07-30 12:00 UTC by lordsarcastic

# Description

What - Fixed a bug where SLOs are returned unevaluated causing entities in Port to be stale
Why - 
How - Added an `evalute=true` query parameter to force evaluation

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots
![image](https://github.com/user-attachments/assets/7034893d-6f85-4bfa-a040-d88f3ec307e4)

## API Documentation
[Get all SLOs](https://docs.dynatrace.com/docs/dynatrace-api/environment-api/service-level-objectives/get-all)

2024-07-30 12:22 UTC, PeyGis requested changes
Looks good, just one suggestion

2024-07-30 12:22 UTC, PeyGis commented on integrations/dynatrace/CHANGELOG.md
> +- Fix problem where API calls return unevaluated SLOs causing stale records in Port (0.1.34)
```suggestion
- Fix problem where API calls return unevaluated SLOs causing stale records in Port
```

2024-07-30 12:27 UTC, matan84 approved these changes
LGTM

2024-07-31 14:31 UTC, PeyGis approved these changes
LGTM

2024-07-31 16:08 UTC, merged