[Integration][Datadog] Add _target='blank' attribute to spec links
port-labs/ocean pull request #851
Opened 2024-07-31 11:44 UTC by phalbert

# Description

Update the description content and the attribute target="_blank" to all <a> tags such that the final becomes <a href=”some_link” target=”_blank”></a>. Doing this will point the url to open a new browser tab instead of the current browser.

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Documentation (added/updated documentation)

## Screenshots

Include screenshots from your environment showing how the resources of the integration will look.

## API Documentation

Provide links to the API documentation used for this integration.

2024-07-31 11:47 UTC, PeyGis requested changes
LGTM

2024-07-31 11:47 UTC, PeyGis commented on integrations/datadog/CHANGELOG.md
> +- Add _target='blank' attribute to spec links to open a new browser tab instead of the current browser.
```suggestion
- Added _target='blank' attribute to spec links to open a new browser tab instead of the current browser.
```

2024-08-01 17:51 UTC, Tankilevitch approved these changes

2024-08-02 11:02 UTC, PeyGis requested changes

2024-08-02 11:02 UTC, PeyGis commented on integrations/datadog/.port/spec.yaml
> +    description: Datadog Base URL (e.g., "https://api.datadoghq.com" or "https://api.datadoghq.eu"). To identify your base URL, see the <a target=”_blank” href="https://docs.datadoghq.com/getting_sta
```suggestion
    description: Datadog Base URL (e.g., "https://api.datadoghq.com" or "https://api.datadoghq.eu"). To identify your base URL, see the <a target="_blank" href="https://docs.datadoghq.com/getting_started/site/#:~:text=within%20their%20environments.-,Access%20the%20Datadog%20site,-You%20can%20identify">Datadog documentation</a>.
```

2024-08-02 11:02 UTC, PeyGis commented on integrations/datadog/.port/spec.yaml
> +    description: Datadog API key. To create an API key, see the <a target=”_blank” href="https://docs.datadoghq.com/account_management/api-app-keys/#add-an-api-key-or-client-token">Datadog documentat
```suggestion
    description: Datadog API key. To create an API key, see the <a target="_blank" href="https://docs.datadoghq.com/account_management/api-app-keys/#add-an-api-key-or-client-token">Datadog documentation</a>.
```

2024-08-02 11:02 UTC, PeyGis commented on integrations/datadog/.port/spec.yaml
> +    description: Datadog application key. To create an application key, see the <a target=”_blank” href="https://docs.datadoghq.com/account_management/api-app-keys/#add-application-keys">Datadog docu
```suggestion
    description: Datadog application key. To create an application key, see the <a target="_blank" href="https://docs.datadoghq.com/account_management/api-app-keys/#add-application-keys">Datadog documentation</a>.
```

2024-08-02 11:02 UTC, PeyGis commented on integrations/datadog/.port/spec.yaml
> +    description: Datadog webhook token (optional). This is used to secure webhook communication between Datadog and Port. To learn more, see the <a target=”_blank” href="https://docs.datadoghq.com/in
```suggestion
    description: Datadog webhook token (optional). This is used to secure webhook communication between Datadog and Port. To learn more, see the <a target="_blank" href="https://docs.datadoghq.com/integrations/webhooks/#setup">Datadog documentation</a>.
```

2024-08-04 08:50 UTC, Tankilevitch approved these changes
LGTM

2024-08-04 10:42 UTC, Tankilevitch commented on integrations/datadog/.port/spec.yaml
> +    description: Datadog Base URL (e.g., "https://api.datadoghq.com" or "https://api.datadoghq.eu"). To identify your base URL, see the <a target="_blank" href="https://docs.datadoghq.com/getting_sta
```suggestion
    description: Datadog Base URL (e.g., <a target="_blank" href="https://api.datadoghq.com">https://api.datadoghq.com</a> or <a target="_blank" href= "https://api.datadoghq.eu")>https://api.datadoghq.eu</a>. To identify your base URL, see the <a target="_blank" href="https://docs.datadoghq.com/getting_started/site/#:~:text=within%20their%20environments.-,Access%20the%20Datadog%20site,-You%20can%20identify">Datadog documentation</a>.
```

2024-08-04 11:19 UTC, merged