- Update the description content and the attribute target="_blank" to…
port-labs/ocean pull request #858
Opened 2024-07-31 15:04 UTC by kodjomiles

# Description
Update the description content and the attribute target="_blank" to anchor tags in descriptions to open a new browser tab instead of the current browser.

- [ ] Documentation (added/updated documentation)

2024-08-01 21:04 UTC, Tankilevitch commented on integrations/firehydrant/CHANGELOG.md
> +- Added _target='blank' attribute to spec links to open a new browser tab instead of the current browser. (#58)
wrong version in changelog, also why removed the space separating from each version it supposed to be two lines

2024-08-01 21:04 UTC, Tankilevitch commented on integrations/firehydrant/pyproject.toml
missing version bump

2024-08-02 10:25 UTC, PeyGis requested changes

2024-08-02 10:25 UTC, PeyGis commented on integrations/firehydrant/.port/spec.yaml
> +    description: API token for your FireHydrant account, for example, "jakdlfja933948anz.cnapaira". It can be found on your <a target="_blank" href="https://app.firehydrant.io/organizations/bots">Fir
```suggestion
    description: The API token for your FireHydrant account used for authentication. To create a token, see the  <a target="_blank" href="https://docs.firehydrant.com/docs/api-keys">FireHydrant document</a>
```

2024-08-02 10:25 UTC, PeyGis commented on integrations/firehydrant/.port/spec.yaml
> +    description: FireHydrant API URL, (e.g., "https://api.firehydrant.io"). To identify your base URL, see the <a target="_blank" href="https://developers.firehydrant.com/#/</a>
```suggestion
    description: The FireHydrant API URL. If not provided, the default value is https://api.firehydrant.io
```

2024-08-02 10:27 UTC, PeyGis approved these changes

2024-08-04 08:49 UTC, Tankilevitch approved these changes
LGTM

2024-08-04 08:49 UTC, merged