[Integration][OpsGenie] Added _target='blank' attribute to spec links
port-labs/ocean pull request #859
Opened 2024-07-31 15:24 UTC by kodjomiles

#Description
- Update the description content and the attribute target="_blank" to anchor tags in descriptions to open a new browser tab instead of the current browser.

- [ ] Documentation (added/updated documentation)

2024-08-02 10:17 UTC, PeyGis requested changes

2024-08-02 10:17 UTC, PeyGis commented on integrations/opsgenie/.port/spec.yaml
> +    description: Opsgenie can have two different API URLs, and the one you need depends on where your Opgenie instance is located. Customers in the EU region should use <a target="_blank" href="https
```suggestion
    description: Opsgenie can have two different API URLs, and the one you need depends on where your Opgenie instance is located. Customers in the EU region should use https://api.eu.opsgenie.com whereas customers in the US region should use https://api.opsgenie.com. If the OpsGenie API URL is not provided, the default value is https://api.opsgenie.com
```

2024-08-02 10:27 UTC, PeyGis approved these changes

2024-08-04 08:49 UTC, Tankilevitch approved these changes
LGTM

2024-08-04 08:49 UTC, merged