[Integration][Snyk, PD, Argo, NewRelic, ServiceNow] Add target=blank to integrations
port-labs/ocean pull request #862
Opened 2024-07-31 16:11 UTC by PeyGis

# Description

What - Added target=blank attribute to all html links in the spec.yaml for Snyk, SonarQube, ArgoCD, NewRelic, ServiceNow and PagerDuty
Why -
How -

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New Integration (non-breaking change which adds a new integration)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Non-breaking change (fix of existing functionality that will not change current behavior)
- [ ] Documentation (added/updated documentation)

## Screenshots

Include screenshots from your environment showing how the resources of the integration will look.

## API Documentation

Provide links to the API documentation used for this integration.

2024-08-01 12:20 UTC, matan84 requested changes
Nice, left one comment

2024-08-01 12:20 UTC, matan84 commented on integrations/argocd/CHANGELOG.md
Create new version for each integration

2024-08-04 09:09 UTC, Tankilevitch commented on integrations/newrelic/.port/spec.yaml
> +    description: URL for New Relic GraphQL API. If not provided, the default value will be https://api.newrelic.com/graphql. Users in the EU region should use https://api.eu.newrelic.com/graphql. For
```suggestion
    description: URL for New Relic GraphQL API. If not provided, the default value will be https://api.newrelic.com/graphql. Users in the EU region should use <a href="https://api.eu.newrelic.com/graphql" target="_blank"> https://api.eu.newrelic.com/graphql</a>. For more information on GraphQL URL, see the <a href="https://docs.newrelic.com/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph/" target="_blank"> New Relic documentation</a>.
```

2024-08-04 09:10 UTC, Tankilevitch commented on integrations/sonarqube/.port/spec.yaml
> +    description: The SonarQube URL to connect to. This is required if you are using SonarQube on-premise. If you are using SonarCloud, the default URL is https://sonarcloud.io
```suggestion
    description: The SonarQube URL to connect to. This is required if you are using SonarQube on-premise. If you are using SonarCloud, the default URL is <a href="https://sonarcloud.io" target="_blank">https://sonarcloud.io</a>
```

2024-08-04 09:12 UTC, Tankilevitch approved these changes

2024-08-04 10:34 UTC, merged