Fix unpacking issue in unregister raw function
port-labs/ocean pull request #870
Opened 2024-08-01 09:49 UTC by mk-armah

# Description

What - Unregister raw throws a value error

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Bug fix (non-breaking change which fixes an issue)

## Screenshots

Include screenshots from your environment showing how the resources of the integration will look.

## API Documentation

Provide links to the API documentation used for this integration.

2024-08-01 12:17 UTC, matan84 requested changes
Good job, left one comment

2024-08-01 12:17 UTC, matan84 commented on CHANGELOG.md
> +- Fix unpacking error in unregister raw
Add more data here- what was broken, and how it was fixed

2024-08-04 08:26 UTC, yairsimantov20 approved these changes
🌊 
Good job!

2024-08-04 08:28 UTC, matan84 approved these changes
LGTM

2024-08-04 08:45 UTC, merged