[Integration][Azure DevOps, Launchdarkly, Terraform Cloud ] Add _target='blank' attribute to spec
port-labs/ocean pull request #872
Opened 2024-08-01 12:11 UTC by mk-armah

# Description

What - Change url links in spec parameters to point to open a new tab instead of in the existing 

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Non-breaking change (fix of existing functionality that will not change current behavior)

## Screenshots

Include screenshots from your environment showing how the resources of the integration will look.

## API Documentation

Provide links to the API documentation used for this integration.

2024-08-01 12:40 UTC, PeyGis requested changes
LGTM

2024-08-01 12:40 UTC, PeyGis commented on integrations/launchdarkly/CHANGELOG.md
> +- Added target='blank' attribute to links in config and secrets description to make them open in new tab (PORT-9537)
```suggestion
- Added target='blank' attribute to links in config and secrets description to make them open in new tab
```

2024-08-01 12:40 UTC, PeyGis commented on integrations/azure-devops/CHANGELOG.md
> +- Added target='blank' attribute to links in config and secrets description to make them open in new tab (PORT-9537)
```suggestion
- Added target='blank' attribute to links in config and secrets description to make them open in new tab
```

2024-08-01 12:41 UTC, PeyGis approved these changes

2024-08-01 12:43 UTC, Tankilevitch approved these changes

2024-08-02 10:33 UTC, PeyGis approved these changes

2024-08-02 10:39 UTC, merged