[Integration][Statuspage] Add _target='blank' attribute to spec links
port-labs/ocean pull request #875
Opened 2024-08-01 18:12 UTC by oiadebayo

# Description

What - Added `_target='blank'` attribute to specification links to ensure they open in a new browser tab instead of the current browser tab.
Why - To enhance user experience by allowing users to keep their current page open while exploring specification links in new tabs. This prevents disruptions and allows for easier reference between the current page and the new tab.
Added _target='blank' attribute to spec links to open a new browser tab instead of the current browser
How - Updated the HTML attributes of the specification links by adding `_target='blank'`.

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New Integration (non-breaking change which adds a new integration)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Non-breaking change (fix of existing functionality that will not change current behavior)
- [ ] Documentation (added/updated documentation)

2024-08-02 10:42 UTC, PeyGis requested changes
left some comment

2024-08-02 10:42 UTC, PeyGis commented on integrations/aws/.port/spec.yaml
> +    description: The AWS User Access Key ID used for authentication. For more information, visit the <a href=”https://docs.aws.amazon.com/singlesignon/latest/userguide/howtogetcredentials.html” targe
```suggestion
    description: The AWS User Access Key ID used for authentication. For more information, visit the <a href="https://docs.aws.amazon.com/singlesignon/latest/userguide/howtogetcredentials.html" target="_blank">AWS documentation</a>
```

2024-08-02 10:42 UTC, PeyGis commented on integrations/aws/.port/spec.yaml
> +    description: The AWS User Secret Access Key used for authentication. For more information, see the <a href=”https://docs.aws.amazon.com/singlesignon/latest/userguide/howtogetcredentials.html” tar
Check the string quote. Use "" instead of ””

2024-08-04 08:47 UTC, Tankilevitch commented on integrations/aws/.port/spec.yaml
> +    description: The AWS User Secret Access Key used for authentication. For more information, see the <a href=”https://docs.aws.amazon.com/singlesignon/latest/userguide/howtogetcredentials.html” tar
```suggestion
    description: The AWS User Secret Access Key used for authentication. For more information, see the <a href="https://docs.aws.amazon.com/singlesignon/latest/userguide/howtogetcredentials.html" target="_blank">AWS documentation</a>.
```

2024-08-04 08:47 UTC, Tankilevitch commented on integrations/gcp/.port/spec.yaml
> +    description: Base64 encoding of your Google Cloud's ADC Credentials configuration file. For more information, see the <a href=”https://docs.getport.io/build-your-software-catalog/sync-data-to-cat
```suggestion
    description: Base64 encoding of your Google Cloud's ADC Credentials configuration file. For more information, see the <a href="https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation" target="_blank">Google documentation</a>
```

2024-08-04 08:47 UTC, Tankilevitch commented on integrations/statuspage/.port/spec.yaml
> +    description: Statuspage API key. To find your API key, see the <a href="https://support.atlassian.com/statuspage/docs/create-and-manage-api-keys/" target=”_blank”>Statuspage documentation</a>.
```suggestion
    description: Statuspage API key. To find your API key, see the <a href="https://support.atlassian.com/statuspage/docs/create-and-manage-api-keys/" target="_blank">Statuspage documentation</a>.
```

2024-08-04 08:48 UTC, Tankilevitch commented on integrations/statuspage/pyproject.toml
> +port_ocean = {extras = ["cli"], version = "^0.9.7"}
```suggestion
port_ocean = {version = "^0.9.7", extras = ["cli"]}
```

2024-08-04 08:52 UTC, Tankilevitch commented on integrations/statuspage/pyproject.toml
> +
```suggestion
```

2024-08-04 08:52 UTC, Tankilevitch approved these changes

2024-08-04 09:05 UTC, merged