[Datadog] Add custom tag names for metric filters
port-labs/ocean pull request #962
Opened 2024-08-28 17:31 UTC by phalbert

# Description

This PR introduces a feature that allows clients to specify custom tag names for hosts, in addition to the default universal Datadog tags (env and service). This enhancement provides flexibility for clients who have hosts tagged with different tags than the default ones used by Datadog.

### Description
The current system defaults to using the universal Datadog tags env and service for host identification and selection. However, some clients (e.g., IU) may have hosts tagged with different tags. To address this need, the following changes have been made:

- Modified the kind selector to allow the specification of custom tag names.
- Default behavior remains unchanged, using env and service tags if no custom tags are specified.
- Updated the `datadogSelector` configuration to include fields for specifying custom tags.

```yaml
kind: serviceMetric
selector:
  query: "true"
  datadogSelector:
    metric: "avg:system.disk.used"
    env: 
      tag: "environment"  # Custom tag specified by the user
      values: "*"
    service: 
      tag: "servicename"  # Custom tag specified by the user
      values: "*"
    timeframe: 5
```

### Additional Notes
- **Backward Compatibility**: The implementation ensures backward compatibility with existing configurations that use only the default env and service tags.
- **Documentation**: Updated documentation and examples have been provided to guide users on how to specify custom tags in their configurations.

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New Integration (non-breaking change which adds a new integration)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Non-breaking change (fix of existing functionality that will not change current behavior)
- [ ] Documentation (added/updated documentation)

<h4> All tests should be run against the port production environment(using a testing org). </h4>

### Core testing checklist

- [ ] Integration able to create all default resources from scratch
- [ ] Resync finishes successfully
- [ ] Resync able to create entities
- [ ] Resync able to update entities
- [ ] Resync able to detect and delete entities
- [ ] Scheduled resync able to abort existing resync and start a new one
- [ ] Tested with at least 2 integrations from scratch
- [ ] Tested with Kafka and Polling event listeners

### Integration testing checklist

- [ ] Integration able to create all default resources from scratch
- [ ] Resync able to create entities
- [ ] Resync able to update entities
- [ ] Resync able to detect and delete entities
- [ ] Resync finishes successfully
- [ ] If new resource kind is added or updated in the integration, add example raw data, mapping and expected result to the `examples` folder in the integration directory. 
- [ ] If resource kind is updated, run the integration with the example data and check if the expected result is achieved
- [ ] If new resource kind is added or updated, validate that live-events for that resource are working as expected
- [ ] Docs PR link [here](#)

### Preflight checklist

- [ ] Handled rate limiting
- [ ] Handled pagination
- [ ] Implemented the code in async
- [ ] Support Multi account

## Screenshots

Include screenshots from your environment showing how the resources of the integration will look.

## API Documentation

Provide links to the API documentation used for this integration.

2024-08-29 11:13 UTC, Tankilevitch commented on integrations/datadog/client.py
> +        logger.info(f"env_tag: {env_tag}, service_tag: {service_tag}")
redundant? maybe add it as part of the log above

2024-08-29 18:13 UTC, Tankilevitch requested changes

2024-08-29 18:13 UTC, Tankilevitch commented on integrations/datadog/examples/mappings.yaml
please add raw data example in another file

2024-08-29 18:13 UTC, Tankilevitch commented on integrations/datadog/client.py
> +        logger.info(f"service_tag: {service_tag}, service_value: {service_value}")
I think this should be inside the `main.py` and not in the client. as the client needs to be just get the variables and not be familiar with the event.resource_config.

2024-08-30 16:52 UTC, PeyGis requested changes

2024-08-30 16:52 UTC, PeyGis commented on integrations/datadog/client.py
> +        logger.info(f"service_tag: {service_tag}, service_value: {service_value}")
Can these logs be on the same line?

2024-09-01 11:39 UTC, Tankilevitch commented on integrations/datadog/examples/metric.response.json
also add result expected json file

2024-09-01 11:39 UTC, Tankilevitch commented on integrations/datadog/main.py
> +    # Extract parameters from event.resource_config
redundant comment

2024-09-02 10:42 UTC, phalbert commented on integrations/datadog/main.py
> +    # Extract parameters from event.resource_config
removed now

2024-09-02 10:42 UTC, phalbert commented on integrations/datadog/examples/metric.response.json
added now

2024-09-02 11:04 UTC, Tankilevitch approved these changes
LGTM

2024-09-02 11:05 UTC, merged